#!/bin/bash

set -euo pipefail

PLOT_PATH="plot"
PLOT_DATA_PATH="data"


BUILD_TYPE="Release"
if [[ $# -gt 0 ]]; then
    BUILD_TYPE="$1"
fi

BUILD_PATH="build"
BUILD_PATH_TYPED="${BUILD_PATH}/${BUILD_TYPE}"
PARALLEL=4



LINE="==============================================="

clear(){
    rm -rf $1
    mkdir $1
}

build(){
    cmake \
        -S . \
        -B $BUILD_PATH_TYPED \
        -DCMAKE_C_COMPILER=gcc-13 \
        -DCMAKE_CXX_COMPILER=g++-13 \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        

    cmake \
        --build $BUILD_PATH_TYPED \
        --parallel $PARALLEL
}

run(){
    TARGET=$1
    echo -e "\nRunning target ${TARGET}\n"
    echo $LINE
    echo ""
    $TARGET
    echo ""
    echo $LINE
    echo -e "\nDone\n"
}

build

clear $PLOT_PATH
clear $PLOT_DATA_PATH

run "${BUILD_PATH_TYPED}/Task1"